# Generated by Django 4.2.7 on 2023-11-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ladrillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='productos/imagenes_productos')),
                ('precio', models.FloatField()),
            ],
        ),
    ]
